graph TD
    Comp_com["Component: com"]
    Comp_patterns["Component: patterns"]
    Comp_behavioral["Component: behavioral"]
    Comp_observer["Component: observer"]
    Comp_strategy["Component: strategy"]
    Comp_templatemethod["Component: templatemethod"]
    Comp_creational["Component: creational"]
    Comp_builder["Component: builder"]
    Comp_factory["Component: factory"]
    Comp_singleton["Component: singleton"]
    Comp_structural["Component: structural"]
    Comp_adapter["Component: adapter"]
    Comp_decorator["Component: decorator"]
    Comp_facade["Component: facade"]
