stateDiagram-v2
    [*] --> Uninitialized_NewsAgency
    Uninitialized_NewsAgency --> Active_NewsAgency : setNews()
    Uninitialized_NewsAgency --> Active_NewsAgency : attach()
    Uninitialized_NewsAgency --> Active_NewsAgency : detach()
    Uninitialized_NewsAgency --> Active_NewsAgency : notifyObservers()
    Active_NewsAgency --> [*]
    [*] --> Uninitialized_NewsChannel
    Uninitialized_NewsChannel --> Active_NewsChannel : update()
    Active_NewsChannel --> [*]
    [*] --> Uninitialized_CreditCardStrategy
    Uninitialized_CreditCardStrategy --> Active_CreditCardStrategy : pay()
    Active_CreditCardStrategy --> [*]
    [*] --> Uninitialized_PaypalStrategy
    Uninitialized_PaypalStrategy --> Active_PaypalStrategy : pay()
    Active_PaypalStrategy --> [*]
    [*] --> Uninitialized_ShoppingCart
    Uninitialized_ShoppingCart --> Active_ShoppingCart : setPaymentStrategy()
    Uninitialized_ShoppingCart --> Active_ShoppingCart : checkout()
    Active_ShoppingCart --> [*]
    [*] --> Uninitialized_CsvDataMiner
    Uninitialized_CsvDataMiner --> Active_CsvDataMiner : openFile()
    Uninitialized_CsvDataMiner --> Active_CsvDataMiner : extractData()
    Uninitialized_CsvDataMiner --> Active_CsvDataMiner : parseData()
    Active_CsvDataMiner --> [*]
    [*] --> Uninitialized_DataMiner
    Uninitialized_DataMiner --> Active_DataMiner : mine()
    Uninitialized_DataMiner --> Active_DataMiner : openFile()
    Uninitialized_DataMiner --> Active_DataMiner : extractData()
    Uninitialized_DataMiner --> Active_DataMiner : parseData()
    Uninitialized_DataMiner --> Active_DataMiner : closeFile()
    Active_DataMiner --> [*]
    [*] --> Uninitialized_PdfDataMiner
    Uninitialized_PdfDataMiner --> Active_PdfDataMiner : openFile()
    Uninitialized_PdfDataMiner --> Active_PdfDataMiner : extractData()
    Uninitialized_PdfDataMiner --> Active_PdfDataMiner : parseData()
    Active_PdfDataMiner --> [*]
    [*] --> Uninitialized_Computer
    Uninitialized_Computer --> Active_Computer : setCpu()
    Uninitialized_Computer --> Active_Computer : setRam()
    Uninitialized_Computer --> Active_Computer : setStorage()
    Uninitialized_Computer --> Active_Computer : setGraphicsCardEnabled()
    Uninitialized_Computer --> Active_Computer : getCpu()
    Uninitialized_Computer --> Active_Computer : getRam()
    Uninitialized_Computer --> Active_Computer : getStorage()
    Uninitialized_Computer --> Active_Computer : isGraphicsCardEnabled()
    Active_Computer --> [*]
    [*] --> Uninitialized_ComputerBuilder
    Uninitialized_ComputerBuilder --> Active_ComputerBuilder : buildCpu()
    Uninitialized_ComputerBuilder --> Active_ComputerBuilder : buildRam()
    Uninitialized_ComputerBuilder --> Active_ComputerBuilder : buildStorage()
    Uninitialized_ComputerBuilder --> Active_ComputerBuilder : setGraphicsCard()
    Uninitialized_ComputerBuilder --> Active_ComputerBuilder : build()
    Active_ComputerBuilder --> [*]
    [*] --> Uninitialized_Director
    Uninitialized_Director --> Active_Director : constructGamingComputer()
    Active_Director --> [*]
    [*] --> Uninitialized_Logistics
    Uninitialized_Logistics --> Active_Logistics : planDelivery()
    Uninitialized_Logistics --> Active_Logistics : createTransport()
    Active_Logistics --> [*]
    [*] --> Uninitialized_RoadLogistics
    Uninitialized_RoadLogistics --> Active_RoadLogistics : createTransport()
    Active_RoadLogistics --> [*]
    [*] --> Uninitialized_SeaLogistics
    Uninitialized_SeaLogistics --> Active_SeaLogistics : createTransport()
    Active_SeaLogistics --> [*]
    [*] --> Uninitialized_Ship
    Uninitialized_Ship --> Active_Ship : deliver()
    Active_Ship --> [*]
    [*] --> Uninitialized_Truck
    Uninitialized_Truck --> Active_Truck : deliver()
    Active_Truck --> [*]
    [*] --> Uninitialized_DatabaseConnectionPool
    Uninitialized_DatabaseConnectionPool --> Active_DatabaseConnectionPool : getInstance()
    Uninitialized_DatabaseConnectionPool --> Active_DatabaseConnectionPool : executeQuery()
    Active_DatabaseConnectionPool --> [*]
    [*] --> Uninitialized_AudioPlayer
    Uninitialized_AudioPlayer --> Active_AudioPlayer : play()
    Active_AudioPlayer --> [*]
    [*] --> Uninitialized_MediaAdapter
    Uninitialized_MediaAdapter --> Active_MediaAdapter : play()
    Active_MediaAdapter --> [*]
    [*] --> Uninitialized_Mp4Player
    Uninitialized_Mp4Player --> Active_Mp4Player : playVlc()
    Uninitialized_Mp4Player --> Active_Mp4Player : playMp4()
    Active_Mp4Player --> [*]
    [*] --> Uninitialized_VlcPlayer
    Uninitialized_VlcPlayer --> Active_VlcPlayer : playVlc()
    Uninitialized_VlcPlayer --> Active_VlcPlayer : playMp4()
    Active_VlcPlayer --> [*]
    [*] --> Uninitialized_CondimentDecorator
    Uninitialized_CondimentDecorator --> Active_CondimentDecorator : getDescription()
    Active_CondimentDecorator --> [*]
    [*] --> Uninitialized_Espresso
    Uninitialized_Espresso --> Active_Espresso : getDescription()
    Uninitialized_Espresso --> Active_Espresso : cost()
    Active_Espresso --> [*]
    [*] --> Uninitialized_Mocha
    Uninitialized_Mocha --> Active_Mocha : getDescription()
    Uninitialized_Mocha --> Active_Mocha : cost()
    Active_Mocha --> [*]
    [*] --> Uninitialized_Whip
    Uninitialized_Whip --> Active_Whip : getDescription()
    Uninitialized_Whip --> Active_Whip : cost()
    Active_Whip --> [*]
    [*] --> Uninitialized_AudioMixer
    Uninitialized_AudioMixer --> Active_AudioMixer : fix()
    Active_AudioMixer --> [*]
    [*] --> Uninitialized_BitrateReader
    Uninitialized_BitrateReader --> Active_BitrateReader : read()
    Active_BitrateReader --> [*]
    [*] --> Uninitialized_VideoConversionFacade
    Uninitialized_VideoConversionFacade --> Active_VideoConversionFacade : convertVideo()
    Active_VideoConversionFacade --> [*]
