//! Template Method & Builder Design Patterns for SCPG Compilation Pipeline (§10.1).
//!
//! Provides a standardized stage execution template enforcing invariants, timing telemetry,
//! and binary validation, alongside a fluent pipeline builder.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

use crate::ast::{ASTStage, ASTStageInput, BPASTArtifact};
use crate::cfg::serializer::CFGArtifact;
use crate::cfg::Phase4Stage;
use crate::cg::Phase6Stage;
use crate::core::io::mmap::MemoryMappedFile;
use crate::core::logger::log_info;
use crate::core::types::cg::CallGraphArtifact;
use crate::ingestion::manifest::SourceManifest;
use crate::ingestion::{IngestionStage, TokenCorpusArtifact};
use crate::psa::types::PathSummaryArtifact;
use crate::psa::Phase8Stage;
use crate::scpg::diagram::factory::DiagramFormat;
use crate::scpg::{OpenHeartEngine, Phase10Stage};
use crate::ssa::serializer::SSAArtifact;
use crate::ssa::Phase5Stage;
use crate::symbol::{Phase3Stage, SymbolTableArtifact};
use crate::tra::types::TraceabilityArtifact;
use crate::tra::Phase7Stage;
use crate::uma::types::UMLMetadataArtifact;
use crate::uma::Phase9Stage;

// ── Template Method Pattern: Stage Execution Template ────────────────────────

/// Template Method Trait for SCPG Compilation Stages.
pub trait PipelineStageTemplate<Input, Output> {
    /// Stage identifier for telemetry.
    fn stage_name(&self) -> &'static str;

    /// Phase number (1 through 10).
    fn phase_number(&self) -> u8;

    /// Step 1: Pre-execution telemetry and initialization hook.
    fn before_stage(&self, _input: &Input) {
        log_info(&format!(
            "══► Starting Stage {}: {}...",
            self.phase_number(),
            self.stage_name()
        ));
    }

    /// Step 2: Core compilation transformation (primitive operation).
    fn run_stage(&self, input: &Input, output_path: &Path) -> Result<Output, String>;

    /// Step 3: Mathematical and structural invariant verification.
    fn verify_invariants(&self, _output: &Output) -> Result<(), String> {
        Ok(())
    }

    /// Step 4: Post-execution telemetry and digest logging hook.
    fn after_stage(&self, _output: &Output, duration: std::time::Duration) {
        log_info(&format!(
            "✓ Stage {} [{}] Complete in {:.2}ms",
            self.phase_number(),
            self.stage_name(),
            duration.as_secs_f64() * 1000.0
        ));
    }

    /// Template Method: Enforces the invariant execution lifecycle.
    fn execute(&self, input: &Input, output_path: &Path) -> Result<Output, String> {
        self.before_stage(input);
        let start = Instant::now();
        let output = self.run_stage(input, output_path)?;
        self.verify_invariants(&output)?;
        let elapsed = start.elapsed();
        self.after_stage(&output, elapsed);
        Ok(output)
    }
}

// ── Builder Pattern: Fluent Pipeline Construction ─────────────────────────────

/// Complete set of compiled binary artifacts generated by the 10-phase pipeline.
pub struct PipelineArtifacts {
    pub tca: TokenCorpusArtifact,
    pub bpa: BPASTArtifact,
    pub sta: SymbolTableArtifact,
    pub cfa: CFGArtifact,
    pub ssa: SSAArtifact,
    pub cga: CallGraphArtifact,
    pub tra: TraceabilityArtifact,
    pub psa: PathSummaryArtifact,
    pub uma: UMLMetadataArtifact,
    pub engine: OpenHeartEngine,
}

/// Fluent Builder for configuring and executing the 10-Phase SCPG Compilation Pipeline.
pub struct SCPGPipelineBuilder {
    source_files: Vec<PathBuf>,
    output_dir: PathBuf,
    diagram_formats: Vec<DiagramFormat>,
}

impl Default for SCPGPipelineBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl SCPGPipelineBuilder {
    pub fn new() -> Self {
        Self {
            source_files: Vec::new(),
            output_dir: std::env::temp_dir(),
            diagram_formats: vec![DiagramFormat::PlantUML, DiagramFormat::Mermaid],
        }
    }

    /// Adds a source file to the pipeline manifest.
    pub fn with_source_file<P: Into<PathBuf>>(mut self, path: P) -> Self {
        self.source_files.push(path.into());
        self
    }

    /// Adds multiple source files to the pipeline manifest.
    pub fn with_source_files<I, P>(mut self, paths: I) -> Self
    where
        I: IntoIterator<Item = P>,
        P: Into<PathBuf>,
    {
        for p in paths {
            self.source_files.push(p.into());
        }
        self
    }

    /// Sets the target directory for serialized binary artifacts (.tca, .bpa, etc.).
    pub fn with_output_dir<P: Into<PathBuf>>(mut self, dir: P) -> Self {
        self.output_dir = dir.into();
        self
    }

    /// Adds a diagram export format.
    pub fn with_diagram_format(mut self, format: DiagramFormat) -> Self {
        if !self.diagram_formats.contains(&format) {
            self.diagram_formats.push(format);
        }
        self
    }

    /// Executes all 10 compilation phases sequentially with full invariant guarantees.
    pub fn execute(self) -> Result<PipelineArtifacts, String> {
        if self.source_files.is_empty() {
            return Err("Cannot execute SCPG pipeline with zero source files".to_string());
        }

        fs::create_dir_all(&self.output_dir)
            .map_err(|e| format!("Failed to create output directory: {}", e))?;

        let tca_path = self.output_dir.join("corpus.tca");
        let bpa_path = self.output_dir.join("ast.bpa");
        let sta_path = self.output_dir.join("symbols.sta");
        let cfa_path = self.output_dir.join("cfg.cfa");
        let ssa_path = self.output_dir.join("ssa.ssa");
        let cga_path = self.output_dir.join("callgraph.cga");
        let tra_path = self.output_dir.join("traceability.tra");
        let psa_path = self.output_dir.join("paths.psa");
        let uma_path = self.output_dir.join("metadata.uma");
        let scpg_path = self.output_dir.join("graph.scpg");

        // Phase 1: Ingestion
        let manifest = SourceManifest::new(self.source_files);
        let tca = IngestionStage::run(manifest, &tca_path)
            .map_err(|e| format!("Phase 1 Ingestion Error: {:?}", e))?;
        let tca_bytes =
            fs::read(&tca_path).map_err(|e| format!("Failed to read TCA bytes: {}", e))?;

        // Phase 2: AST
        let mmap_tca = MemoryMappedFile::open(&tca_path)
            .map_err(|e| format!("Failed to mmap TCA: {:?}", e))?;
        let stage_input = ASTStageInput { tca: mmap_tca };
        let bpa = ASTStage::run(&stage_input, &bpa_path)
            .map_err(|e| format!("Phase 2 AST Error: {:?}", e))?;
        let bpa_bytes =
            fs::read(&bpa_path).map_err(|e| format!("Failed to read BPA bytes: {}", e))?;

        // Phase 3: Symbols & Scope Graph
        let sta = Phase3Stage::run(&tca, &bpa, &tca_bytes, &bpa_bytes)
            .map_err(|e| format!("Phase 3 Symbol Table Error: {:?}", e))?;
        let sta_bytes = sta.serialize();
        fs::write(&sta_path, &sta_bytes)
            .map_err(|e| format!("Failed to write STA bytes: {}", e))?;

        // Phase 4: CFG
        let cfa = Phase4Stage::run(&bpa, &sta, &sta_bytes, &bpa_bytes, &cfa_path)
            .map_err(|e| format!("Phase 4 CFG Error: {:?}", e))?;
        let cfa_bytes =
            fs::read(&cfa_path).map_err(|e| format!("Failed to read CFA bytes: {}", e))?;

        // Phase 5: SSA
        let ssa = Phase5Stage::run(&bpa, &sta, &cfa, &cfa_bytes, &ssa_path)
            .map_err(|e| format!("Phase 5 SSA Error: {:?}", e))?;
        let ssa_bytes =
            fs::read(&ssa_path).map_err(|e| format!("Failed to read SSA bytes: {}", e))?;

        // Phase 6: Call Graph
        let cga = Phase6Stage::run(&bpa, &sta, &cfa, &ssa, &ssa_bytes, &sta_bytes, &cga_path)
            .map_err(|e| format!("Phase 6 Call Graph Error: {:?}", e))?;

        // Phase 7: Traceability
        let tra = Phase7Stage::run(&tca, &bpa, &sta, &cfa, &ssa, &cga, &tra_path);
        let tra_bytes =
            fs::read(&tra_path).map_err(|e| format!("Failed to read TRA bytes: {}", e))?;

        // Phase 8: PSA
        let psa = Phase8Stage::run(&cfa, &ssa, &cga, &cfa_bytes, &psa_path);

        // Phase 9: UMA
        let uma = Phase9Stage::run(
            &tca, &bpa, &sta, &cfa, &ssa, &cga, &tra, &psa, &tra_bytes, &uma_path,
        );

        // Phase 10: SCPG Binary & Engine Bootstrap
        let engine = Phase10Stage::run(
            &tca, &bpa, &sta, &cfa, &ssa, &cga, &tra, &uma, &psa, &scpg_path,
        );

        Ok(PipelineArtifacts {
            tca,
            bpa,
            sta,
            cfa,
            ssa,
            cga,
            tra,
            psa,
            uma,
            engine,
        })
    }
}
