//! PlantUMLExporter — exports UMLMetadataArtifact records to PlantUML syntax (§10.4).

use crate::uma::types::*;

pub struct PlantUMLExporter;

impl PlantUMLExporter {
    pub fn export_class_diagram(classes: &[ClassRecord]) -> String {
        let mut puml = String::from("@startuml\n");
        puml.push_str("' Generated by OpenHeart SCPG Engine Phase 10\n");
        for class_rec in classes {
            puml.push_str(&format!("class Class_{}\n", class_rec.sym_id));
        }
        puml.push_str("@enduml\n");
        puml
    }
}
