graph TD
    subgraph Act_6["Function: setNews"]
        Start_6([Start: setNews])
        Node_6_0["Block_0"]
        Node_6_1["Block_1"]
        Node_6_2["Block_2"]
        Node_6_0 --> Node_6_1
        Node_6_1 --> Node_6_2
    end

    subgraph Act_8["Function: attach"]
        Start_8([Start: attach])
        Node_8_0["Block_0"]
        Node_8_1["Block_1"]
        Node_8_2["Block_2"]
        Node_8_0 --> Node_8_1
        Node_8_1 --> Node_8_2
    end

    subgraph Act_10["Function: detach"]
        Start_10([Start: detach])
        Node_10_0["Block_0"]
        Node_10_1["Block_1"]
        Node_10_2["Block_2"]
        Node_10_0 --> Node_10_1
        Node_10_1 --> Node_10_2
    end

    subgraph Act_12["Function: notifyObservers"]
        Start_12([Start: notifyObservers])
        Node_12_0["Block_0"]
        Node_12_1["Block_1"]
        Node_12_2["Block_2"]
        Node_12_3["Block_3"]
        Node_12_4["Block_4"]
        Node_12_5["Block_5"]
        Node_12_0 --> Node_12_1
        Node_12_1 --> Node_12_2
        Node_12_2 --> Node_12_5
        Node_12_5 --> Node_12_2
        Node_12_2 --> Node_12_3
        Node_12_3 --> Node_12_4
    end

    subgraph Act_17["Function: update"]
        Start_17([Start: update])
        Node_17_0["Block_0"]
        Node_17_1["Block_1"]
        Node_17_2["Block_2"]
        Node_17_0 --> Node_17_1
        Node_17_1 --> Node_17_2
    end

    subgraph Act_39["Function: pay"]
        Start_39([Start: pay])
        Node_39_0["Block_0"]
        Node_39_1["Block_1"]
        Node_39_2["Block_2"]
        Node_39_0 --> Node_39_1
        Node_39_1 --> Node_39_2
    end

    subgraph Act_51["Function: pay"]
        Start_51([Start: pay])
        Node_51_0["Block_0"]
        Node_51_1["Block_1"]
        Node_51_2["Block_2"]
        Node_51_0 --> Node_51_1
        Node_51_1 --> Node_51_2
    end

    subgraph Act_57["Function: setPaymentStrategy"]
        Start_57([Start: setPaymentStrategy])
        Node_57_0["Block_0"]
        Node_57_1["Block_1"]
        Node_57_2["Block_2"]
        Node_57_0 --> Node_57_1
        Node_57_1 --> Node_57_2
    end

