graph TD
    subgraph Act_10["Function: createDataInitializer"]
        Start_10([Start: createDataInitializer])
        Node_10_0["Block_0"]
        Node_10_1["Block_1"]
        Node_10_2["Block_2"]
        Node_10_0 --> Node_10_1
        Node_10_1 --> Node_10_2
    end

    subgraph Act_25["Function: build"]
        Start_25([Start: build])
        Node_25_0["Block_0"]
        Node_25_1["Block_1"]
        Node_25_2["Block_2"]
        Node_25_0 --> Node_25_1
        Node_25_1 --> Node_25_2
    end

    subgraph Act_26["Function: if"]
        Start_26([Start: if])
        Node_26_0["Block_0"]
        Node_26_1["Block_1"]
        Node_26_2["Block_2"]
        Node_26_0 --> Node_26_1
        Node_26_1 --> Node_26_2
    end

    subgraph Act_34["Function: setUpTrainer"]
        Start_34([Start: setUpTrainer])
        Node_34_0["Block_0"]
        Node_34_1["Block_1"]
        Node_34_2["Block_2"]
        Node_34_3["Block_3"]
        Node_34_4["Block_4"]
        Node_34_0 --> Node_34_1
        Node_34_1 --> Node_34_2
        Node_34_2 --> Node_34_3
        Node_34_1 --> Node_34_3
        Node_34_3 --> Node_34_4
    end

    subgraph Act_39["Function: createTrainer"]
        Start_39([Start: createTrainer])
        Node_39_0["Block_0"]
        Node_39_1["Block_1"]
        Node_39_2["Block_2"]
        Node_39_0 --> Node_39_1
        Node_39_1 --> Node_39_2
    end

    subgraph Act_50["Function: onUploadSuccess"]
        Start_50([Start: onUploadSuccess])
        Node_50_0["Block_0"]
        Node_50_1["Block_1"]
        Node_50_2["Block_2"]
        Node_50_0 --> Node_50_1
        Node_50_1 --> Node_50_2
    end

    subgraph Act_56["Function: createCheckpoint"]
        Start_56([Start: createCheckpoint])
        Node_56_0["Block_0"]
        Node_56_1["Block_1"]
        Node_56_2["Block_2"]
        Node_56_0 --> Node_56_1
        Node_56_1 --> Node_56_2
    end

    subgraph Act_58["Function: loadCheckpoint"]
        Start_58([Start: loadCheckpoint])
        Node_58_0["Block_0"]
        Node_58_1["Block_1"]
        Node_58_2["Block_2"]
        Node_58_3["Block_3"]
        Node_58_4["Block_4"]
        Node_58_0 --> Node_58_1
        Node_58_1 --> Node_58_3
        Node_58_3 --> Node_58_4
        Node_58_1 --> Node_58_2
        Node_58_2 --> Node_58_4
    end

