graph LR
    Actor -->|1: update()| Observer
    Actor -->|1: attach()| Subject
    Actor -->|1: detach()| Subject
    Actor -->|1: notifyObservers()| Subject
    Actor -->|1: CreditCardStrategy()| CreditCardStrategy
    Actor -->|1: pay()| PaymentStrategy
    Actor -->|1: PaypalStrategy()| PaypalStrategy
    Actor -->|1: setPaymentStrategy()| ShoppingCart
    Actor -->|1: openFile()| DataMiner
    Actor -->|1: extractData()| DataMiner
    Actor -->|1: parseData()| DataMiner
    Actor -->|1: setCpu()| Computer
    Actor -->|1: setRam()| Computer
    Actor -->|1: setStorage()| Computer
    Actor -->|1: setGraphicsCardEnabled()| Computer
    Actor -->|1: getCpu()| Computer
    Actor -->|1: getRam()| Computer
    Actor -->|1: getStorage()| Computer
    Actor -->|1: isGraphicsCardEnabled()| Computer
    Actor -->|1: ComputerBuilder()| ComputerBuilder
    Actor -->|1: build()| ComputerBuilder
    Actor -->|1: createTransport()| Logistics
    Actor -->|1: deliver()| Transport
    Actor -->|1: DatabaseConnectionPool()| DatabaseConnectionPool
    Actor -->|1: playVlc()| AdvancedMediaPlayer
    Actor -->|1: playMp4()| AdvancedMediaPlayer
    Actor -->|1: MediaAdapter()| MediaAdapter
    Actor -->|1: play()| MediaPlayer
    Actor -->|1: playVlc()| Mp4Player
    Actor -->|1: playMp4()| VlcPlayer
    Actor -->|1: getDescription()| Beverage
    Actor -->|1: cost()| Beverage
    Actor -->|1: CondimentDecorator()| CondimentDecorator
    Actor -->|1: getDescription()| CondimentDecorator
    Actor -->|1: getDescription()| Espresso
    Actor -->|1: cost()| Espresso
    Actor -->|1: Mocha()| Mocha
    Actor -->|1: Whip()| Whip
