graph TD
    subgraph Comp_CurrentState["Composite: CurrentState"]
        Inner_CurrentState_CurrentState["inner: CurrentState"]
    end

    subgraph Comp_IDAssigner["Composite: IDAssigner"]
        Inner_IDAssigner_IDAssigner["inner: IDAssigner"]
    end

