graph TD
    Comp_AppBackend["Component: AppBackend"]
    Comp_DataManager["Component: DataManager"]
    Comp_DataLoaderAndInitializer["Component: DataLoaderAndInitializer"]
    Comp_Factory["Component: Factory"]
    Comp_PackageTypeTrainer["Component: PackageTypeTrainer"]
    Comp_LocalTrainingModule["Component: LocalTrainingModule"]
    Comp_TrainingExecutor["Component: TrainingExecutor"]
    Comp_TrainingStateManager["Component: TrainingStateManager"]
    Comp_Network["Component: Network"]
    Comp_ModelUpdateTransmission["Component: ModelUpdateTransmission"]
    Comp_RegisteredInfo["Component: RegisteredInfo"]
    Comp_Server_DAO["Component: Server_DAO"]
    Comp_ResourceManagement["Component: ResourceManagement"]
    Comp_OperationControl["Component: OperationControl"]
    Comp_ResourceManager["Component: ResourceManager"]
    Comp_TaskContainer["Component: TaskContainer"]
    Comp_Validator["Component: Validator"]
    Comp_ModelInferenceValidator["Component: ModelInferenceValidator"]
    Comp_AppFrontend["Component: AppFrontend"]
    Comp_Flush["Component: Flush"]
    Comp_Interface["Component: Interface"]
    Comp_AboutUs["Component: AboutUs"]
    Comp_Auth["Component: Auth"]
    Comp_DeviceAuthorization["Component: DeviceAuthorization"]
    Comp_DeviceUnregister["Component: DeviceUnregister"]
    Comp_ForgetPassword["Component: ForgetPassword"]
    Comp_GetStarted["Component: GetStarted"]
    Comp_Home["Component: Home"]
    Comp_Insights["Component: Insights"]
    Comp_DeviceInsights["Component: DeviceInsights"]
    Comp_ModelTraining["Component: ModelTraining"]
    Comp_UsageInsights["Component: UsageInsights"]
    Comp_RegisteredInfo["Component: RegisteredInfo"]
    Comp_RewardBank["Component: RewardBank"]
    Comp_Settings["Component: Settings"]
    Comp_TrainingLogsDisplay["Component: TrainingLogsDisplay"]
    Comp_AppGlobal["Component: AppGlobal"]
    Comp_Utils["Component: Utils"]
    Comp_com["Component: com"]
    Comp_example["Component: example"]
    Comp_fractal["Component: fractal"]
