@startuml
skinparam backgroundColor transparent
skinparam monochrome false
skinparam shadowing false
skinparam roundcorner 6
skinparam defaultFontName "Space Grotesk", "Segoe UI", sans-serif
skinparam defaultFontColor #e5e5e5
skinparam defaultFontSize 12
skinparam ArrowColor #38bdf8
skinparam ArrowThickness 1.5
skinparam ComponentBorderColor #38bdf8
skinparam ComponentBackgroundColor #14171f
skinparam ComponentFontColor #ffffff

package "OpenHeart Engine Architecture" {
  component [ingestionUnit: LexicalIngestion] as Ingest
  component [symbolResolver: SymbolEngine] as Symbol
  component [dominatorEngine: CooperCFG] as Dom
  component [bddVerifier: ROBDDLibrary] as BDD
  component [scpgSynthesizer: SCPGCompiler] as SCPG

  Ingest -port_tca-> Symbol : port_in
  Symbol -port_sta-> Dom : port_cfg
  Dom -port_ssa-> BDD : port_bdd
  BDD -port_psa-> SCPG : port_scpg
}

@enduml
