graph LR
    subgraph Node_AppBackend["Deployment Node: AppBackend"]
        Art_AppBackend["artifact: AppBackend.module"]
    end

    subgraph Node_DataManager["Deployment Node: DataManager"]
        Art_DataManager["artifact: DataManager.module"]
    end

    subgraph Node_DataLoaderAndInitializer["Deployment Node: DataLoaderAndInitializer"]
        Art_DataLoaderAndInitializer["artifact: DataLoaderAndInitializer.module"]
    end

    subgraph Node_Factory["Deployment Node: Factory"]
        Art_Factory["artifact: Factory.module"]
    end

    subgraph Node_PackageTypeTrainer["Deployment Node: PackageTypeTrainer"]
        Art_PackageTypeTrainer["artifact: PackageTypeTrainer.module"]
    end

    subgraph Node_LocalTrainingModule["Deployment Node: LocalTrainingModule"]
        Art_LocalTrainingModule["artifact: LocalTrainingModule.module"]
    end

    subgraph Node_TrainingExecutor["Deployment Node: TrainingExecutor"]
        Art_TrainingExecutor["artifact: TrainingExecutor.module"]
    end

    subgraph Node_TrainingStateManager["Deployment Node: TrainingStateManager"]
        Art_TrainingStateManager["artifact: TrainingStateManager.module"]
    end

    subgraph Node_Network["Deployment Node: Network"]
        Art_Network["artifact: Network.module"]
    end

    subgraph Node_ModelUpdateTransmission["Deployment Node: ModelUpdateTransmission"]
        Art_ModelUpdateTransmission["artifact: ModelUpdateTransmission.module"]
    end

    subgraph Node_RegisteredInfo["Deployment Node: RegisteredInfo"]
        Art_RegisteredInfo["artifact: RegisteredInfo.module"]
    end

    subgraph Node_Server_DAO["Deployment Node: Server_DAO"]
        Art_Server_DAO["artifact: Server_DAO.module"]
    end

    subgraph Node_ResourceManagement["Deployment Node: ResourceManagement"]
        Art_ResourceManagement["artifact: ResourceManagement.module"]
    end

    subgraph Node_OperationControl["Deployment Node: OperationControl"]
        Art_OperationControl["artifact: OperationControl.module"]
    end

    subgraph Node_ResourceManager["Deployment Node: ResourceManager"]
        Art_ResourceManager["artifact: ResourceManager.module"]
    end

    subgraph Node_TaskContainer["Deployment Node: TaskContainer"]
        Art_TaskContainer["artifact: TaskContainer.module"]
    end

    subgraph Node_Validator["Deployment Node: Validator"]
        Art_Validator["artifact: Validator.module"]
    end

    subgraph Node_ModelInferenceValidator["Deployment Node: ModelInferenceValidator"]
        Art_ModelInferenceValidator["artifact: ModelInferenceValidator.module"]
    end

    subgraph Node_AppFrontend["Deployment Node: AppFrontend"]
        Art_AppFrontend["artifact: AppFrontend.module"]
    end

    subgraph Node_Flush["Deployment Node: Flush"]
        Art_Flush["artifact: Flush.module"]
    end

    subgraph Node_Interface["Deployment Node: Interface"]
        Art_Interface["artifact: Interface.module"]
    end

    subgraph Node_AboutUs["Deployment Node: AboutUs"]
        Art_AboutUs["artifact: AboutUs.module"]
    end

    subgraph Node_Auth["Deployment Node: Auth"]
        Art_Auth["artifact: Auth.module"]
    end

    subgraph Node_DeviceAuthorization["Deployment Node: DeviceAuthorization"]
        Art_DeviceAuthorization["artifact: DeviceAuthorization.module"]
    end

    subgraph Node_DeviceUnregister["Deployment Node: DeviceUnregister"]
        Art_DeviceUnregister["artifact: DeviceUnregister.module"]
    end

    subgraph Node_ForgetPassword["Deployment Node: ForgetPassword"]
        Art_ForgetPassword["artifact: ForgetPassword.module"]
    end

    subgraph Node_GetStarted["Deployment Node: GetStarted"]
        Art_GetStarted["artifact: GetStarted.module"]
    end

    subgraph Node_Home["Deployment Node: Home"]
        Art_Home["artifact: Home.module"]
    end

    subgraph Node_Insights["Deployment Node: Insights"]
        Art_Insights["artifact: Insights.module"]
    end

    subgraph Node_DeviceInsights["Deployment Node: DeviceInsights"]
        Art_DeviceInsights["artifact: DeviceInsights.module"]
    end

    subgraph Node_ModelTraining["Deployment Node: ModelTraining"]
        Art_ModelTraining["artifact: ModelTraining.module"]
    end

    subgraph Node_UsageInsights["Deployment Node: UsageInsights"]
        Art_UsageInsights["artifact: UsageInsights.module"]
    end

    subgraph Node_RegisteredInfo["Deployment Node: RegisteredInfo"]
        Art_RegisteredInfo["artifact: RegisteredInfo.module"]
    end

    subgraph Node_RewardBank["Deployment Node: RewardBank"]
        Art_RewardBank["artifact: RewardBank.module"]
    end

    subgraph Node_Settings["Deployment Node: Settings"]
        Art_Settings["artifact: Settings.module"]
    end

    subgraph Node_TrainingLogsDisplay["Deployment Node: TrainingLogsDisplay"]
        Art_TrainingLogsDisplay["artifact: TrainingLogsDisplay.module"]
    end

    subgraph Node_AppGlobal["Deployment Node: AppGlobal"]
        Art_AppGlobal["artifact: AppGlobal.module"]
    end

    subgraph Node_Utils["Deployment Node: Utils"]
        Art_Utils["artifact: Utils.module"]
    end

    subgraph Node_com["Deployment Node: com"]
        Art_com["artifact: com.module"]
    end

    subgraph Node_example["Deployment Node: example"]
        Art_example["artifact: example.module"]
    end

    subgraph Node_fractal["Deployment Node: fractal"]
        Art_fractal["artifact: fractal.module"]
    end

