graph LR
    subgraph Node_json["Deployment Node: json"]
        Art_json["artifact: json.module"]
    end

    subgraph Node_owns["Deployment Node: owns"]
        Art_owns["artifact: owns.module"]
    end

    subgraph Node_config["Deployment Node: config"]
        Art_config["artifact: config.module"]
    end

    subgraph Node_relative["Deployment Node: relative"]
        Art_relative["artifact: relative.module"]
    end

    subgraph Node_Lets["Deployment Node: Lets"]
        Art_Lets["artifact: Lets.module"]
    end

    subgraph Node_terface["Deployment Node: terface"]
        Art_terface["artifact: terface.module"]
    end

    subgraph Node_version["Deployment Node: version"]
        Art_version["artifact: version.module"]
    end

    subgraph Node_stallation["Deployment Node: stallation"]
        Art_stallation["artifact: stallation.module"]
    end

