graph TD
    subgraph Scenario_AppFrontend["Scenario: AppFrontend"]
        Disp_onUploadSuccess["dispatch onUploadSuccess()"]
    end

    subgraph Scenario_Suppress["Scenario: Suppress"]
        Disp_run["dispatch run()"]
        Disp_startLiveUpdates["dispatch startLiveUpdates()"]
        Disp_startLiveUpdates["dispatch startLiveUpdates()"]
        Disp_startLiveUpdates["dispatch startLiveUpdates()"]
    end

    subgraph Scenario_if["Scenario: if"]
        Disp_POST_Ping["dispatch POST_Ping()"]
    end

    subgraph Scenario_AppFrontend["Scenario: AppFrontend"]
        Disp_isPaused["dispatch isPaused()"]
    end

