classDiagram
    class obj_SupportedLanguage {
        <<instance: SupportedLanguage>>
    }
    class obj_Priority {
        <<instance: Priority>>
    }
    class obj_NFRCategory {
        <<instance: NFRCategory>>
    }
    class obj_ScreenType {
        <<instance: ScreenType>>
    }
    class obj_RelationshipType {
        <<instance: RelationshipType>>
    }
    class obj_AttributeType {
        <<instance: AttributeType>>
    }
    class obj_RawRequirementFeatures {
        <<instance: RawRequirementFeatures>>
    }
    class obj_FunctionalRequirement {
        <<instance: FunctionalRequirement>>
    }
    class obj_FunctionalRequirementSet {
        <<instance: FunctionalRequirementSet>>
    }
    class obj_NonFunctionalRequirement {
        <<instance: NonFunctionalRequirement>>
    }
    class obj_NonFunctionalRequirementSet {
        <<instance: NonFunctionalRequirementSet>>
    }
    class obj_SitemapNode {
        <<instance: SitemapNode>>
    }
    class obj_NavigationEdge {
        <<instance: NavigationEdge>>
    }
    class obj_Sitemap {
        <<instance: Sitemap>>
    }
    class obj_EntityAttribute {
        <<instance: EntityAttribute>>
    }
    class obj_EntityRelationship {
        <<instance: EntityRelationship>>
    }
    class obj_EntitySet {
        <<instance: EntitySet>>
    }
    class obj_ComponentNode {
        <<instance: ComponentNode>>
    }
    class obj_ComponentTree {
        <<instance: ComponentTree>>
    }
    class obj_ComponentTreeSet {
        <<instance: ComponentTreeSet>>
    }
    class obj_TechStackSelection {
        <<instance: TechStackSelection>>
    }
    class obj_PipelineTiming {
        <<instance: PipelineTiming>>
    }
    class obj_FullSRSOutput {
        <<instance: FullSRSOutput>>
    }
    class obj_CompilerBuilder {
        <<instance: CompilerBuilder>>
    }
    class obj_CompilerEngine {
        <<instance: CompilerEngine>>
    }
    class obj_NavigationType {
        <<instance: NavigationType>>
    }
    class obj_StateManagerType {
        <<instance: StateManagerType>>
    }
    class obj_CompilerError {
        <<instance: CompilerError>>
    }
    class obj_ValidationError {
        <<instance: ValidationError>>
    }
    class obj_CompilationError {
        <<instance: CompilationError>>
    }
    class obj_FileWriter {
        <<instance: FileWriter>>
    }
    class obj_AppEntryGenerator {
        <<instance: AppEntryGenerator>>
    }
    class obj_ComponentsGenerator {
        <<instance: ComponentsGenerator>>
    }
    class obj_ConfigFilesGenerator {
        <<instance: ConfigFilesGenerator>>
    }
    class obj_EnvFilesGenerator {
        <<instance: EnvFilesGenerator>>
    }
    class obj_NavigationGenerator {
        <<instance: NavigationGenerator>>
    }
    class obj_StateManagementGenerator {
        <<instance: StateManagementGenerator>>
    }
    class obj_StaticDataGenerator {
        <<instance: StaticDataGenerator>>
    }
    class obj_UtilitiesGenerator {
        <<instance: UtilitiesGenerator>>
    }
    class obj_ApiError {
        <<instance: ApiError>>
    }
    class obj_NavRoute {
        <<instance: NavRoute>>
    }
    class obj_StateManager {
        <<instance: StateManager>>
    }
    class obj_AppConfig {
        <<instance: AppConfig>>
    }
    class obj_ComponentGenerationError {
        <<instance: ComponentGenerationError>>
    }
    class obj_MissingComponentNameError {
        <<instance: MissingComponentNameError>>
    }
    class obj_InvalidDesignTokensError {
        <<instance: InvalidDesignTokensError>>
    }
    class obj_InvalidLayoutSpecificationError {
        <<instance: InvalidLayoutSpecificationError>>
    }
    class obj_UnsupportedComponentTypeError {
        <<instance: UnsupportedComponentTypeError>>
    }
    class obj_MalformedHierarchyError {
        <<instance: MalformedHierarchyError>>
    }
    class obj_ComponentValidationError {
        <<instance: ComponentValidationError>>
    }
    class obj_ComponentGenerator {
        <<instance: ComponentGenerator>>
    }
    class obj_ComponentTreeIn {
        <<instance: ComponentTreeIn>>
    }
    class obj_GenerateComponentsRequest {
        <<instance: GenerateComponentsRequest>>
    }
    class obj_GeneratedComponent {
        <<instance: GeneratedComponent>>
    }
    class obj_FailedComponent {
        <<instance: FailedComponent>>
    }
    class obj_GenerateComponentsResponse {
        <<instance: GenerateComponentsResponse>>
    }
    class obj_FirebaseHelper {
        <<instance: FirebaseHelper>>
    }
    class obj_CustomerFeedback {
        <<instance: CustomerFeedback>>
    }
    class obj_EngineReframer {
        <<instance: EngineReframer>>
    }
    class obj_CurrentState {
        <<instance: CurrentState>>
    }
    class obj_SRSRequest {
        <<instance: SRSRequest>>
    }
    class obj_LLMAPIError {
        <<instance: LLMAPIError>>
    }
    class obj_LLMClient {
        <<instance: LLMClient>>
    }
    class obj_ExtractedComponentNode {
        <<instance: ExtractedComponentNode>>
    }
    class obj_ExtractedAttribute {
        <<instance: ExtractedAttribute>>
    }
    class obj_ExtractedRelationship {
        <<instance: ExtractedRelationship>>
    }
    class obj_ExtractedEntity {
        <<instance: ExtractedEntity>>
    }
    class obj_ExtractedFR {
        <<instance: ExtractedFR>>
    }
    class obj_ExtractedNFR {
        <<instance: ExtractedNFR>>
    }
    class obj_SRSPipelineError {
        <<instance: SRSPipelineError>>
    }
    class obj_ExtractedFeatures {
        <<instance: ExtractedFeatures>>
    }
    class obj_ExtractedScreen {
        <<instance: ExtractedScreen>>
    }
    class obj_ExtractedEdge {
        <<instance: ExtractedEdge>>
    }
    class obj_ExtractedSitemap {
        <<instance: ExtractedSitemap>>
    }
    class obj_ExtractedStack {
        <<instance: ExtractedStack>>
    }
    class obj_Tester {
        <<instance: Tester>>
    }
    class obj_IDAssigner {
        <<instance: IDAssigner>>
    }
    class obj_CodeEditor {
        <<instance: CodeEditor>>
    }
    class obj_ICodeEditor {
        <<instance: ICodeEditor>>
    }
    class obj_EnvSetupManager {
        <<instance: EnvSetupManager>>
    }
    class obj_Jinie {
        <<instance: Jinie>>
    }
    class obj_DependencyCheck {
        <<instance: DependencyCheck>>
    }
    class obj_DependencyReport {
        <<instance: DependencyReport>>
    }
    class obj_FileHandler {
        <<instance: FileHandler>>
    }
    class obj_IFileHandler {
        <<instance: IFileHandler>>
    }
    class obj_MarkdownConverter {
        <<instance: MarkdownConverter>>
    }
    class obj_IMarkdownConverter {
        <<instance: IMarkdownConverter>>
    }
    class obj_Reformatter {
        <<instance: Reformatter>>
    }
    class obj_IReformatter {
        <<instance: IReformatter>>
    }
    class obj_VerificationValidation {
        <<instance: VerificationValidation>>
    }
    class obj_REFERENCE {
        <<instance: REFERENCE>>
    }
    class obj_AppStore {
        <<instance: AppStore>>
    }
    class obj_AppContextType {
        <<instance: AppContextType>>
    }
    class obj_The {
        <<instance: The>>
    }
    class obj_Module {
        <<instance: Module>>
    }
    class obj_Keeping {
        <<instance: Keeping>>
    }
    class obj_JSONDecodeError {
        <<instance: JSONDecodeError>>
    }
    class obj_FormattingOptions {
        <<instance: FormattingOptions>>
    }
    class obj_ButtonProps {
        <<instance: ButtonProps>>
    }
    class obj_SectionProps {
        <<instance: SectionProps>>
    }
    class obj_StatusBadgeProps {
        <<instance: StatusBadgeProps>>
    }
    class obj_DeploymentSectionProps {
        <<instance: DeploymentSectionProps>>
    }
    class obj_DesignSectionProps {
        <<instance: DesignSectionProps>>
    }
    class obj_GeneratedComponentsSectionProps {
        <<instance: GeneratedComponentsSectionProps>>
    }
    class obj_PreviewSectionProps {
        <<instance: PreviewSectionProps>>
    }
    class obj_LayoutNode {
        <<instance: LayoutNode>>
    }
    class obj_ScreenRendererProps {
        <<instance: ScreenRendererProps>>
    }
    class obj_PromptComposerProps {
        <<instance: PromptComposerProps>>
    }
    class obj_SRSSectionProps {
        <<instance: SRSSectionProps>>
    }
    class obj_WorkflowStepperProps {
        <<instance: WorkflowStepperProps>>
    }
