flowchart TB
    subgraph Pkg_json["package: json"]
        Mod_json["json"]
    end
    subgraph Pkg_owns["package: owns"]
        Mod_owns["owns"]
    end
    subgraph Pkg_config["package: config"]
        Mod_config["config"]
    end
    subgraph Pkg_relative["package: relative"]
        Mod_relative["relative"]
    end
    subgraph Pkg_Lets["package: Lets"]
        Mod_Lets["Lets"]
    end
    subgraph Pkg_terface["package: terface"]
        Mod_terface["terface"]
    end
    subgraph Pkg_version["package: version"]
        Mod_version["version"]
    end
    subgraph Pkg_stallation["package: stallation"]
        Mod_stallation["stallation"]
    end
