flowchart TB
    subgraph Pkg_com["package: com"]
        Mod_com["com"]
    end
    subgraph Pkg_patterns["package: patterns"]
        Mod_patterns["patterns"]
    end
    subgraph Pkg_behavioral["package: behavioral"]
        Mod_behavioral["behavioral"]
    end
    subgraph Pkg_observer["package: observer"]
        Mod_observer["observer"]
    end
    subgraph Pkg_strategy["package: strategy"]
        Mod_strategy["strategy"]
    end
    subgraph Pkg_templatemethod["package: templatemethod"]
        Mod_templatemethod["templatemethod"]
    end
    subgraph Pkg_creational["package: creational"]
        Mod_creational["creational"]
    end
    subgraph Pkg_builder["package: builder"]
        Mod_builder["builder"]
    end
    subgraph Pkg_factory["package: factory"]
        Mod_factory["factory"]
    end
    subgraph Pkg_singleton["package: singleton"]
        Mod_singleton["singleton"]
    end
    subgraph Pkg_structural["package: structural"]
        Mod_structural["structural"]
    end
    subgraph Pkg_adapter["package: adapter"]
        Mod_adapter["adapter"]
    end
    subgraph Pkg_decorator["package: decorator"]
        Mod_decorator["decorator"]
    end
    subgraph Pkg_facade["package: facade"]
        Mod_facade["facade"]
    end
    subgraph Pkg_com_patterns_behavioral_observer["package: com.patterns.behavioral.observer"]
        Mod_com_patterns_behavioral_observer["com_patterns_behavioral_observer"]
    end
    subgraph Pkg_com_patterns_behavioral_strategy["package: com.patterns.behavioral.strategy"]
        Mod_com_patterns_behavioral_strategy["com_patterns_behavioral_strategy"]
    end
    subgraph Pkg_com_patterns_behavioral_templatemethod["package: com.patterns.behavioral.templatemethod"]
        Mod_com_patterns_behavioral_templatemethod["com_patterns_behavioral_templatemethod"]
    end
    subgraph Pkg_com_patterns_creational_builder["package: com.patterns.creational.builder"]
        Mod_com_patterns_creational_builder["com_patterns_creational_builder"]
    end
    subgraph Pkg_com_patterns_creational_factory["package: com.patterns.creational.factory"]
        Mod_com_patterns_creational_factory["com_patterns_creational_factory"]
    end
    subgraph Pkg_com_patterns_creational_singleton["package: com.patterns.creational.singleton"]
        Mod_com_patterns_creational_singleton["com_patterns_creational_singleton"]
    end
    subgraph Pkg_com_patterns_structural_adapter["package: com.patterns.structural.adapter"]
        Mod_com_patterns_structural_adapter["com_patterns_structural_adapter"]
    end
    subgraph Pkg_com_patterns_structural_decorator["package: com.patterns.structural.decorator"]
        Mod_com_patterns_structural_decorator["com_patterns_structural_decorator"]
    end
    subgraph Pkg_com_patterns_structural_facade["package: com.patterns.structural.facade"]
        Mod_com_patterns_structural_facade["com_patterns_structural_facade"]
    end
