sequenceDiagram
    autonumber
    Actor->>Observer: update()
    Actor->>Subject: attach()
    Actor->>Subject: detach()
    Actor->>Subject: notifyObservers()
    Actor->>CreditCardStrategy: CreditCardStrategy()
    Actor->>PaymentStrategy: pay()
    Actor->>PaypalStrategy: PaypalStrategy()
    Actor->>ShoppingCart: setPaymentStrategy()
    Actor->>DataMiner: openFile()
    Actor->>DataMiner: extractData()
    Actor->>DataMiner: parseData()
    Actor->>Computer: setCpu()
    Actor->>Computer: setRam()
    Actor->>Computer: setStorage()
    Actor->>Computer: setGraphicsCardEnabled()
    Actor->>Computer: getCpu()
    Actor->>Computer: getRam()
    Actor->>Computer: getStorage()
    Actor->>Computer: isGraphicsCardEnabled()
    Actor->>ComputerBuilder: ComputerBuilder()
    Actor->>ComputerBuilder: build()
    Actor->>Logistics: createTransport()
    Actor->>Transport: deliver()
    Actor->>DatabaseConnectionPool: DatabaseConnectionPool()
    Actor->>AdvancedMediaPlayer: playVlc()
    Actor->>AdvancedMediaPlayer: playMp4()
    Actor->>MediaAdapter: MediaAdapter()
    Actor->>MediaPlayer: play()
    Actor->>Mp4Player: playVlc()
    Actor->>VlcPlayer: playMp4()
    Actor->>Beverage: getDescription()
    Actor->>Beverage: cost()
    Actor->>CondimentDecorator: CondimentDecorator()
    Actor->>CondimentDecorator: getDescription()
    Actor->>Espresso: getDescription()
    Actor->>Espresso: cost()
    Actor->>Mocha: Mocha()
    Actor->>Whip: Whip()
