stateDiagram-v2
    [*] --> Uninitialized_Image_DataInitializer_Factory
    Uninitialized_Image_DataInitializer_Factory --> Active_Image_DataInitializer_Factory : createDataInitializer()
    Uninitialized_Image_DataInitializer_Factory --> Active_Image_DataInitializer_Factory : createDataInitializer()
    Active_Image_DataInitializer_Factory --> [*]
    [*] --> Uninitialized_Image_Trainer_Factory
    Uninitialized_Image_Trainer_Factory --> Active_Image_Trainer_Factory : createTrainer()
    Uninitialized_Image_Trainer_Factory --> Active_Image_Trainer_Factory : createTrainer()
    Active_Image_Trainer_Factory --> [*]
    [*] --> Uninitialized_CheckpointManager
    Uninitialized_CheckpointManager --> Active_CheckpointManager : createCheckpoint()
    Uninitialized_CheckpointManager --> Active_CheckpointManager : loadCheckpoint()
    Uninitialized_CheckpointManager --> Active_CheckpointManager : createCheckpoint()
    Uninitialized_CheckpointManager --> Active_CheckpointManager : loadCheckpoint()
    Active_CheckpointManager --> [*]
    [*] --> Uninitialized_networkConfig_ini
    Uninitialized_networkConfig_ini --> Active_networkConfig_ini : getBaseUrl()
    Active_networkConfig_ini --> [*]
    [*] --> Uninitialized_DataDownloader_naf
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : downloadFiles()
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : downloadFiles()
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : getFileSize()
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : downloadFileWithProgress()
    Active_DataDownloader_naf --> [*]
    [*] --> Uninitialized_FileUploader_naf
    Uninitialized_FileUploader_naf --> Active_FileUploader_naf : uploadCheckpoint()
    Active_FileUploader_naf --> [*]
    [*] --> Uninitialized_Parser
    Uninitialized_Parser --> Active_Parser : read()
    Uninitialized_Parser --> Active_Parser : fullScan()
    Uninitialized_Parser --> Active_Parser : discoverDevfreqGpuNodes()
    Uninitialized_Parser --> Active_Parser : discoverProcGpuNodes()
    Uninitialized_Parser --> Active_Parser : tryCandidate()
    Uninitialized_Parser --> Active_Parser : tryParseFile()
    Uninitialized_Parser --> Active_Parser : parseRaw()
    Active_Parser --> [*]
    [*] --> Uninitialized_Image_Task_Factory
    Uninitialized_Image_Task_Factory --> Active_Image_Task_Factory : createTask()
    Uninitialized_Image_Task_Factory --> Active_Image_Task_Factory : createTask()
    Active_Image_Task_Factory --> [*]
    [*] --> Uninitialized_Image_InferenceValidator_Factory
    Uninitialized_Image_InferenceValidator_Factory --> Active_Image_InferenceValidator_Factory : createInferenceValidator()
    Uninitialized_Image_InferenceValidator_Factory --> Active_Image_InferenceValidator_Factory : createInferenceValidator()
    Active_Image_InferenceValidator_Factory --> [*]
    [*] --> Uninitialized_Flusher
    Uninitialized_Flusher --> Active_Flusher : flushCheckpoint()
    Uninitialized_Flusher --> Active_Flusher : flushCurrentTask()
    Uninitialized_Flusher --> Active_Flusher : flushAll()
    Uninitialized_Flusher --> Active_Flusher : flushCheckpoint()
    Uninitialized_Flusher --> Active_Flusher : flushCurrentTask()
    Uninitialized_Flusher --> Active_Flusher : flushAll()
    Active_Flusher --> [*]
    [*] --> Uninitialized_DiamondTrainingView
    Uninitialized_DiamondTrainingView --> Active_DiamondTrainingView : onDraw()
    Uninitialized_DiamondTrainingView --> Active_DiamondTrainingView : setProgress()
    Active_DiamondTrainingView --> [*]
    [*] --> Uninitialized_HomeFragment
    Uninitialized_HomeFragment --> Active_HomeFragment : onCreateView()
    Uninitialized_HomeFragment --> Active_HomeFragment : onDestroyView()
    Active_HomeFragment --> [*]
    [*] --> Uninitialized_HomeViewModel
    Uninitialized_HomeViewModel --> Active_HomeViewModel : getArchitectureModel()
    Uninitialized_HomeViewModel --> Active_HomeViewModel : setArchitectureModel()
    Uninitialized_HomeViewModel --> Active_HomeViewModel : toggleAILifecycle()
    Uninitialized_HomeViewModel --> Active_HomeViewModel : getTrainingProgress()
    Uninitialized_HomeViewModel --> Active_HomeViewModel : getStatusMessage()
    Uninitialized_HomeViewModel --> Active_HomeViewModel : getDetailedStats()
    Uninitialized_HomeViewModel --> Active_HomeViewModel : getLiveStats()
    Active_HomeViewModel --> [*]
    [*] --> Uninitialized_ModelTrainer
    Uninitialized_ModelTrainer --> Active_ModelTrainer : loadModel()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : loadModelFile()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : initializeDataStreams()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : loadBatch()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : initializeWeights()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : trainModel()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : inferModel()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : restoreWeights()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : org_restoreWeights()
    Uninitialized_ModelTrainer --> Active_ModelTrainer : cleanup()
    Active_ModelTrainer --> [*]
    [*] --> Uninitialized_TrainingStateRepository
    Uninitialized_TrainingStateRepository --> Active_TrainingStateRepository : getInstance()
    Active_TrainingStateRepository --> [*]
    [*] --> Uninitialized_DeviceInsightsFragment
    Uninitialized_DeviceInsightsFragment --> Active_DeviceInsightsFragment : onCreateView()
    Uninitialized_DeviceInsightsFragment --> Active_DeviceInsightsFragment : setupObservers()
    Uninitialized_DeviceInsightsFragment --> Active_DeviceInsightsFragment : onDestroyView()
    Active_DeviceInsightsFragment --> [*]
    [*] --> Uninitialized_DeviceInsightsViewModel
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getBatteryPercent()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getIsCharging()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getIsOnline()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getIsWifi()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getIsCellular()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getDeviceStandby()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getNetworkStandby()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getPowerConsumption()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getTempStorage()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getBgTasks()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : button_optimize()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : startLiveUpdates()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : updateStats()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : getFolderSize()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : clearCacheFolder()
    Uninitialized_DeviceInsightsViewModel --> Active_DeviceInsightsViewModel : onCleared()
    Active_DeviceInsightsViewModel --> [*]
    [*] --> Uninitialized_InsightsPagerAdapter
    Uninitialized_InsightsPagerAdapter --> Active_InsightsPagerAdapter : getItemCount()
    Uninitialized_InsightsPagerAdapter --> Active_InsightsPagerAdapter : getItemCount()
    Uninitialized_InsightsPagerAdapter --> Active_InsightsPagerAdapter : createFragment()
    Active_InsightsPagerAdapter --> [*]
    [*] --> Uninitialized_InsightsPagerFragment
    Uninitialized_InsightsPagerFragment --> Active_InsightsPagerFragment : onCreateView()
    Uninitialized_InsightsPagerFragment --> Active_InsightsPagerFragment : onViewCreated()
    Active_InsightsPagerFragment --> [*]
    [*] --> Uninitialized_ModelTrainingFragment
    Uninitialized_ModelTrainingFragment --> Active_ModelTrainingFragment : onCreateView()
    Uninitialized_ModelTrainingFragment --> Active_ModelTrainingFragment : onDestroyView()
    Active_ModelTrainingFragment --> [*]
    [*] --> Uninitialized_ModelTrainingViewModel
    Uninitialized_ModelTrainingViewModel --> Active_ModelTrainingViewModel : getText()
    Uninitialized_ModelTrainingViewModel --> Active_ModelTrainingViewModel : updateModelTrainingGraph()
    Active_ModelTrainingViewModel --> [*]
    [*] --> Uninitialized_TrainingWaveView
    Uninitialized_TrainingWaveView --> Active_TrainingWaveView : setActive()
    Active_TrainingWaveView --> [*]
    [*] --> Uninitialized_HeartBeatView
    Uninitialized_HeartBeatView --> Active_HeartBeatView : setActive()
    Uninitialized_HeartBeatView --> Active_HeartBeatView : updateStats()
    Uninitialized_HeartBeatView --> Active_HeartBeatView : setActive()
    Uninitialized_HeartBeatView --> Active_HeartBeatView : updateStats()
    Uninitialized_HeartBeatView --> Active_HeartBeatView : onDraw()
    Active_HeartBeatView --> [*]
    [*] --> Uninitialized_ResourceStatsChartView
    Uninitialized_ResourceStatsChartView --> Active_ResourceStatsChartView : updateStats()
    Uninitialized_ResourceStatsChartView --> Active_ResourceStatsChartView : onDraw()
    Uninitialized_ResourceStatsChartView --> Active_ResourceStatsChartView : generateRandomTargets()
    Uninitialized_ResourceStatsChartView --> Active_ResourceStatsChartView : onAttachedToWindow()
    Uninitialized_ResourceStatsChartView --> Active_ResourceStatsChartView : onDetachedFromWindow()
    Active_ResourceStatsChartView --> [*]
    [*] --> Uninitialized_FluidWaveLayout
    Uninitialized_FluidWaveLayout --> Active_FluidWaveLayout : set()
    Uninitialized_FluidWaveLayout --> Active_FluidWaveLayout : set()
    Active_FluidWaveLayout --> [*]
    [*] --> Uninitialized_FileOperations
    Uninitialized_FileOperations --> Active_FileOperations : writeJson()
    Uninitialized_FileOperations --> Active_FileOperations : T()
    Uninitialized_FileOperations --> Active_FileOperations : reified()
    Active_FileOperations --> [*]
    [*] --> Uninitialized_BootReceiver
    Uninitialized_BootReceiver --> Active_BootReceiver : onReceive()
    Uninitialized_BootReceiver --> Active_BootReceiver : onReceive()
    Active_BootReceiver --> [*]
    [*] --> Uninitialized_FractalApplication
    Uninitialized_FractalApplication --> Active_FractalApplication : onCreate()
    Uninitialized_FractalApplication --> Active_FractalApplication : initializeHeavyComponents()
    Uninitialized_FractalApplication --> Active_FractalApplication : onCreate()
    Uninitialized_FractalApplication --> Active_FractalApplication : initializeHeavyComponents()
    Active_FractalApplication --> [*]
    [*] --> Uninitialized_NOTIFICATION_ID
    Uninitialized_NOTIFICATION_ID --> Active_NOTIFICATION_ID : createNotification()
    Uninitialized_NOTIFICATION_ID --> Active_NOTIFICATION_ID : createNotificationChannel()
    Uninitialized_NOTIFICATION_ID --> Active_NOTIFICATION_ID : onBind()
    Active_NOTIFICATION_ID --> [*]
    [*] --> Uninitialized_MainActivity
    Uninitialized_MainActivity --> Active_MainActivity : onCreate()
    Uninitialized_MainActivity --> Active_MainActivity : initFirebaseRemoteConfig()
    Uninitialized_MainActivity --> Active_MainActivity : startHardwareSyncThread()
    Uninitialized_MainActivity --> Active_MainActivity : setupNavigationUI()
    Uninitialized_MainActivity --> Active_MainActivity : setupSidebarNav()
    Uninitialized_MainActivity --> Active_MainActivity : attachBaseContext()
    Uninitialized_MainActivity --> Active_MainActivity : animateNavIcons()
    Uninitialized_MainActivity --> Active_MainActivity : dispatchTouchEvent()
    Active_MainActivity --> [*]
    [*] --> Uninitialized_OvernightManagerService
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : onCreate()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : onStartCommand()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : onDestroy()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : onBind()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : runOvernightLoop()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : startGeneration()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : resumeGeneration()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : pauseForDaytime()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : createNotificationChannel()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : buildNotification()
    Uninitialized_OvernightManagerService --> Active_OvernightManagerService : updateNotification()
    Active_OvernightManagerService --> [*]
    [*] --> Uninitialized_NOTIFICATION_ID
    Uninitialized_NOTIFICATION_ID --> Active_NOTIFICATION_ID : minutesUntil()
    Uninitialized_NOTIFICATION_ID --> Active_NOTIFICATION_ID : formatCountdown()
    Active_NOTIFICATION_ID --> [*]
    [*] --> Uninitialized_Image_DataInitializer
    Uninitialized_Image_DataInitializer --> Active_Image_DataInitializer : locadBatch()
    Uninitialized_Image_DataInitializer --> Active_Image_DataInitializer : preprocess()
    Active_Image_DataInitializer --> [*]
    [*] --> Uninitialized_PackageTypeTrainer
    Uninitialized_PackageTypeTrainer --> Active_PackageTypeTrainer : run()
    Active_PackageTypeTrainer --> [*]
    [*] --> Uninitialized_PackageTypeTrainerBuilder
    Uninitialized_PackageTypeTrainerBuilder --> Active_PackageTypeTrainerBuilder : build()
    Uninitialized_PackageTypeTrainerBuilder --> Active_PackageTypeTrainerBuilder : make()
    Uninitialized_PackageTypeTrainerBuilder --> Active_PackageTypeTrainerBuilder : addTask()
    Uninitialized_PackageTypeTrainerBuilder --> Active_PackageTypeTrainerBuilder : addDataInitializer()
    Uninitialized_PackageTypeTrainerBuilder --> Active_PackageTypeTrainerBuilder : addTrainer()
    Uninitialized_PackageTypeTrainerBuilder --> Active_PackageTypeTrainerBuilder : addValidator()
    Uninitialized_PackageTypeTrainerBuilder --> Active_PackageTypeTrainerBuilder : buildFinal()
    Active_PackageTypeTrainerBuilder --> [*]
    [*] --> Uninitialized_ImageTrainer
    Uninitialized_ImageTrainer --> Active_ImageTrainer : setUpTrainer()
    Uninitialized_ImageTrainer --> Active_ImageTrainer : loadModelFile()
    Uninitialized_ImageTrainer --> Active_ImageTrainer : loadModel()
    Uninitialized_ImageTrainer --> Active_ImageTrainer : initializeWeights()
    Uninitialized_ImageTrainer --> Active_ImageTrainer : trainModel()
    Active_ImageTrainer --> [*]
    [*] --> Uninitialized_ModelTransmitter
    Uninitialized_ModelTransmitter --> Active_ModelTransmitter : transmitModel()
    Active_ModelTransmitter --> [*]
    [*] --> Uninitialized_RegistrationManager
    Uninitialized_RegistrationManager --> Active_RegistrationManager : startLiveUpdates()
    Active_RegistrationManager --> [*]
    [*] --> Uninitialized_Runnable
    Uninitialized_Runnable --> Active_Runnable : run()
    Uninitialized_Runnable --> Active_Runnable : stopLiveUpdates()
    Uninitialized_Runnable --> Active_Runnable : generateNewRegistrationData()
    Uninitialized_Runnable --> Active_Runnable : getHardwareId()
    Uninitialized_Runnable --> Active_Runnable : getSerial()
    Uninitialized_Runnable --> Active_Runnable : getTotalRAM()
    Uninitialized_Runnable --> Active_Runnable : getTotalInternalMemorySize()
    Uninitialized_Runnable --> Active_Runnable : getProcessorName()
    Uninitialized_Runnable --> Active_Runnable : getMacAddress()
    Uninitialized_Runnable --> Active_Runnable : formatSize()
    Uninitialized_Runnable --> Active_Runnable : loadRegistrationData()
    Uninitialized_Runnable --> Active_Runnable : saveRegistrationData()
    Active_Runnable --> [*]
    [*] --> Uninitialized_Server_DAO
    Uninitialized_Server_DAO --> Active_Server_DAO : POST_Ping()
    Uninitialized_Server_DAO --> Active_Server_DAO : GET_Task()
    Uninitialized_Server_DAO --> Active_Server_DAO : POST_UploadModelToServer()
    Uninitialized_Server_DAO --> Active_Server_DAO : writeTextPart()
    Uninitialized_Server_DAO --> Active_Server_DAO : POST_RegisterLogin()
    Uninitialized_Server_DAO --> Active_Server_DAO : GET_RegisteredInfo()
    Uninitialized_Server_DAO --> Active_Server_DAO : POST_Forgetpassword_verifyEmail()
    Uninitialized_Server_DAO --> Active_Server_DAO : POST_ForgetPassword_sendEmail()
    Uninitialized_Server_DAO --> Active_Server_DAO : GET_VerifiedLiquidMBs()
    Uninitialized_Server_DAO --> Active_Server_DAO : POST_Unregister()
    Uninitialized_Server_DAO --> Active_Server_DAO : POST_SendRegisteredInfo()
    Active_Server_DAO --> [*]
    [*] --> Uninitialized_OperationControl
    Uninitialized_OperationControl --> Active_OperationControl : waitForOptimalConditions()
    Uninitialized_OperationControl --> Active_OperationControl : waitForNetworkToUpload()
    Uninitialized_OperationControl --> Active_OperationControl : evaluateNetworkOnly()
    Uninitialized_OperationControl --> Active_OperationControl : evaluateDeviceState()
    Uninitialized_OperationControl --> Active_OperationControl : getViolationMessage()
    Active_OperationControl --> [*]
    [*] --> Uninitialized_ResourceManager_Live_DTO
    Uninitialized_ResourceManager_Live_DTO --> Active_ResourceManager_Live_DTO : updateStatistics()
    Uninitialized_ResourceManager_Live_DTO --> Active_ResourceManager_Live_DTO : resolveGpuLoad()
    Uninitialized_ResourceManager_Live_DTO --> Active_ResourceManager_Live_DTO : getActualCpuUsage()
    Active_ResourceManager_Live_DTO --> [*]
    [*] --> Uninitialized_Image_Task
    Uninitialized_Image_Task --> Active_Image_Task : save_data()
    Active_Image_Task --> [*]
    [*] --> Uninitialized_Image_InferenceValidator
    Uninitialized_Image_InferenceValidator --> Active_Image_InferenceValidator : infer()
    Uninitialized_Image_InferenceValidator --> Active_Image_InferenceValidator : inferImageInferenceValidate()
    Active_Image_InferenceValidator --> [*]
    [*] --> Uninitialized_AboutUs_Fragment
    Uninitialized_AboutUs_Fragment --> Active_AboutUs_Fragment : onCreateView()
    Uninitialized_AboutUs_Fragment --> Active_AboutUs_Fragment : onViewCreated()
    Uninitialized_AboutUs_Fragment --> Active_AboutUs_Fragment : setupClickListeners()
    Uninitialized_AboutUs_Fragment --> Active_AboutUs_Fragment : joinUs()
    Uninitialized_AboutUs_Fragment --> Active_AboutUs_Fragment : onDestroyView()
    Active_AboutUs_Fragment --> [*]
    [*] --> Uninitialized_DeviceAuthorization_Fragment
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : onCreateView()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : onViewCreated()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : onResume()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : setupObservers()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : setupClickListeners()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : togglePasswordVisibility()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : fixPasswordFont()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : button_LoginRegister()
    Uninitialized_DeviceAuthorization_Fragment --> Active_DeviceAuthorization_Fragment : onDestroyView()
    Active_DeviceAuthorization_Fragment --> [*]
    [*] --> Uninitialized_DeviceAuthorization_ViewModel
    Uninitialized_DeviceAuthorization_ViewModel --> Active_DeviceAuthorization_ViewModel : loginRegister()
    Uninitialized_DeviceAuthorization_ViewModel --> Active_DeviceAuthorization_ViewModel : startPollingForVerification()
    Uninitialized_DeviceAuthorization_ViewModel --> Active_DeviceAuthorization_ViewModel : updateAuthStatus()
    Uninitialized_DeviceAuthorization_ViewModel --> Active_DeviceAuthorization_ViewModel : onCleared()
    Active_DeviceAuthorization_ViewModel --> [*]
    [*] --> Uninitialized_DeviceUnregister_Fragment
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : onCreateView()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : onViewCreated()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : onStart()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : onStop()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : onResume()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : enforceAuthenticationUI()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : setupObservers()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : setupClickListeners()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : button_unregister()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : uriToByteArray()
    Uninitialized_DeviceUnregister_Fragment --> Active_DeviceUnregister_Fragment : onDestroyView()
    Active_DeviceUnregister_Fragment --> [*]
    [*] --> Uninitialized_DeviceUnregister_ViewModel
    Uninitialized_DeviceUnregister_ViewModel --> Active_DeviceUnregister_ViewModel : unregister()
    Active_DeviceUnregister_ViewModel --> [*]
    [*] --> Uninitialized_ForgetPassword_Fragment
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : onCreateView()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : onViewCreated()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : setupInitialUI()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : setupObservers()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : setupClickListeners()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : attemptSendEmail()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : lockAndSend()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : unlockEmailField()
    Uninitialized_ForgetPassword_Fragment --> Active_ForgetPassword_Fragment : onDestroyView()
    Active_ForgetPassword_Fragment --> [*]
    [*] --> Uninitialized_ForgetPassword_ViewModel
    Uninitialized_ForgetPassword_ViewModel --> Active_ForgetPassword_ViewModel : recover()
    Active_ForgetPassword_ViewModel --> [*]
    [*] --> Uninitialized_GetStarted_Fragment
    Uninitialized_GetStarted_Fragment --> Active_GetStarted_Fragment : onCreateView()
    Uninitialized_GetStarted_Fragment --> Active_GetStarted_Fragment : onDestroyView()
    Active_GetStarted_Fragment --> [*]
    [*] --> Uninitialized_ViewPager2
    Uninitialized_ViewPager2 --> Active_ViewPager2 : onPageSelected()
    Uninitialized_ViewPager2 --> Active_ViewPager2 : updateIndicators()
    Uninitialized_ViewPager2 --> Active_ViewPager2 : setIndicatorState()
    Uninitialized_ViewPager2 --> Active_ViewPager2 : onDestroyView()
    Active_ViewPager2 --> [*]
    [*] --> Uninitialized_WaveLayer
    Uninitialized_WaveLayer --> Active_WaveLayer : onDraw()
    Uninitialized_WaveLayer --> Active_WaveLayer : drawWave()
    Active_WaveLayer --> [*]
    [*] --> Uninitialized_UsageInsights_Fragment
    Uninitialized_UsageInsights_Fragment --> Active_UsageInsights_Fragment : onCreateView()
    Uninitialized_UsageInsights_Fragment --> Active_UsageInsights_Fragment : onViewCreated()
    Uninitialized_UsageInsights_Fragment --> Active_UsageInsights_Fragment : onDestroyView()
    Active_UsageInsights_Fragment --> [*]
    [*] --> Uninitialized_UsageInsights_ViewModel
    Uninitialized_UsageInsights_ViewModel --> Active_UsageInsights_ViewModel : transformLiveStats()
    Uninitialized_UsageInsights_ViewModel --> Active_UsageInsights_ViewModel : getRomUsagePercentage()
    Active_UsageInsights_ViewModel --> [*]
    [*] --> Uninitialized_RegisteredInfo_Fragment
    Uninitialized_RegisteredInfo_Fragment --> Active_RegisteredInfo_Fragment : onCreateView()
    Uninitialized_RegisteredInfo_Fragment --> Active_RegisteredInfo_Fragment : onViewCreated()
    Uninitialized_RegisteredInfo_Fragment --> Active_RegisteredInfo_Fragment : onResume()
    Uninitialized_RegisteredInfo_Fragment --> Active_RegisteredInfo_Fragment : onPause()
    Uninitialized_RegisteredInfo_Fragment --> Active_RegisteredInfo_Fragment : updateUiStats()
    Uninitialized_RegisteredInfo_Fragment --> Active_RegisteredInfo_Fragment : onDestroyView()
    Active_RegisteredInfo_Fragment --> [*]
    [*] --> Uninitialized_RegisteredInfo_ViewModel
    Uninitialized_RegisteredInfo_ViewModel --> Active_RegisteredInfo_ViewModel : refreshFirebaseData()
    Uninitialized_RegisteredInfo_ViewModel --> Active_RegisteredInfo_ViewModel : startPollingForVerification()
    Uninitialized_RegisteredInfo_ViewModel --> Active_RegisteredInfo_ViewModel : startLiveHardwareUpdates()
    Uninitialized_RegisteredInfo_ViewModel --> Active_RegisteredInfo_ViewModel : stopLiveHardwareUpdates()
    Active_RegisteredInfo_ViewModel --> [*]
    [*] --> Uninitialized_Choreographer
    Uninitialized_Choreographer --> Active_Choreographer : doFrame()
    Uninitialized_Choreographer --> Active_Choreographer : onAttachedToWindow()
    Uninitialized_Choreographer --> Active_Choreographer : onDetachedFromWindow()
    Uninitialized_Choreographer --> Active_Choreographer : updatePhysics()
    Uninitialized_Choreographer --> Active_Choreographer : onSensorChanged()
    Uninitialized_Choreographer --> Active_Choreographer : onAccuracyChanged()
    Uninitialized_Choreographer --> Active_Choreographer : spawnSplatters()
    Uninitialized_Choreographer --> Active_Choreographer : getLocalPercentage()
    Uninitialized_Choreographer --> Active_Choreographer : getSurgeCrest()
    Uninitialized_Choreographer --> Active_Choreographer : buildWavePath()
    Uninitialized_Choreographer --> Active_Choreographer : onDraw()
    Uninitialized_Choreographer --> Active_Choreographer : dispatchDraw()
    Active_Choreographer --> [*]
    [*] --> Uninitialized_RewardBank_Fragment
    Uninitialized_RewardBank_Fragment --> Active_RewardBank_Fragment : onCreateView()
    Uninitialized_RewardBank_Fragment --> Active_RewardBank_Fragment : onResume()
    Uninitialized_RewardBank_Fragment --> Active_RewardBank_Fragment : checkAuthStatus()
    Uninitialized_RewardBank_Fragment --> Active_RewardBank_Fragment : setupObservers()
    Uninitialized_RewardBank_Fragment --> Active_RewardBank_Fragment : setupClickListeners()
    Uninitialized_RewardBank_Fragment --> Active_RewardBank_Fragment : onDestroyView()
    Active_RewardBank_Fragment --> [*]
    [*] --> Uninitialized_RewardBank_ViewModel
    Uninitialized_RewardBank_ViewModel --> Active_RewardBank_ViewModel : getInstance()
    Active_RewardBank_ViewModel --> [*]
    [*] --> Uninitialized_BroadcastReceiver
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : onReceive()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : startLiveSync()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : stopLiveSync()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : animateToNewValues()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : onCleared()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : getCurrentDateStr()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : checkAndResetIfNewDay()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : animateFlushToZero()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : finalizeReset()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : addRealVapor()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : verifyVaporToLiquid()
    Uninitialized_BroadcastReceiver --> Active_BroadcastReceiver : refreshUI()
    Active_BroadcastReceiver --> [*]
    [*] --> Uninitialized_Settings_Fragment
    Uninitialized_Settings_Fragment --> Active_Settings_Fragment : onCreateView()
    Uninitialized_Settings_Fragment --> Active_Settings_Fragment : onViewCreated()
    Uninitialized_Settings_Fragment --> Active_Settings_Fragment : onResume()
    Uninitialized_Settings_Fragment --> Active_Settings_Fragment : setupInitialState()
    Uninitialized_Settings_Fragment --> Active_Settings_Fragment : setupListeners()
    Active_Settings_Fragment --> [*]
    [*] --> Uninitialized_SeekBar
    Uninitialized_SeekBar --> Active_SeekBar : onProgressChanged()
    Uninitialized_SeekBar --> Active_SeekBar : onStartTrackingTouch()
    Uninitialized_SeekBar --> Active_SeekBar : onStopTrackingTouch()
    Uninitialized_SeekBar --> Active_SeekBar : updateLabelText()
    Uninitialized_SeekBar --> Active_SeekBar : updateIcon()
    Uninitialized_SeekBar --> Active_SeekBar : onDestroyView()
    Uninitialized_SeekBar --> Active_SeekBar : event_updateSettings()
    Active_SeekBar --> [*]
    [*] --> Uninitialized_Settings_ViewModel
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : getConfig()
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : saveConfig()
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : toggleWifi()
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : toggleData()
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : toggleOvernight()
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : toggleIdle()
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : toggleChargingExclusive()
    Uninitialized_Settings_ViewModel --> Active_Settings_ViewModel : updateChargeLimit()
    Active_Settings_ViewModel --> [*]
    [*] --> Uninitialized_TrainingLogger
    Uninitialized_TrainingLogger --> Active_TrainingLogger : appendLog()
    Active_TrainingLogger --> [*]
    [*] --> Uninitialized_TrainingLogsDisplay_Fragment
    Uninitialized_TrainingLogsDisplay_Fragment --> Active_TrainingLogsDisplay_Fragment : onCreateView()
    Uninitialized_TrainingLogsDisplay_Fragment --> Active_TrainingLogsDisplay_Fragment : onViewCreated()
    Uninitialized_TrainingLogsDisplay_Fragment --> Active_TrainingLogsDisplay_Fragment : onDestroyView()
    Active_TrainingLogsDisplay_Fragment --> [*]
    [*] --> Uninitialized_GlobalState
    Uninitialized_GlobalState --> Active_GlobalState : pingStatusCalculatorAndDispatcher()
    Active_GlobalState --> [*]
    [*] --> Uninitialized_Log
    Uninitialized_Log --> Active_Log : deleteFile()
    Uninitialized_Log --> Active_Log : fileExists()
    Uninitialized_Log --> Active_Log : copyDefaultFromAssets()
    Active_Log --> [*]
    [*] --> Uninitialized_FractalTrainingService
    Uninitialized_FractalTrainingService --> Active_FractalTrainingService : onCreate()
    Uninitialized_FractalTrainingService --> Active_FractalTrainingService : isSystemInDarkMode()
    Uninitialized_FractalTrainingService --> Active_FractalTrainingService : onStartCommand()
    Uninitialized_FractalTrainingService --> Active_FractalTrainingService : startPipelineThread()
    Active_FractalTrainingService --> [*]
    [*] --> Uninitialized_TrainingCallback
    Uninitialized_TrainingCallback --> Active_TrainingCallback : onTaskAcquired()
    Uninitialized_TrainingCallback --> Active_TrainingCallback : onEpochUpdate()
    Uninitialized_TrainingCallback --> Active_TrainingCallback : onUploadSuccess()
    Uninitialized_TrainingCallback --> Active_TrainingCallback : onProgress()
    Uninitialized_TrainingCallback --> Active_TrainingCallback : onValidationUpdate()
    Uninitialized_TrainingCallback --> Active_TrainingCallback : onStatusUpdate()
    Uninitialized_TrainingCallback --> Active_TrainingCallback : updateNotification()
    Active_TrainingCallback --> [*]
    [*] --> Uninitialized_Orchestrator
    Uninitialized_Orchestrator --> Active_Orchestrator : executeTrainingPipeline()
    Active_Orchestrator --> [*]
    [*] --> Uninitialized_DataDownloader_naf
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : isPaused()
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : isCancelled()
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : onDownloadFinished()
    Uninitialized_DataDownloader_naf --> Active_DataDownloader_naf : onError()
    Active_DataDownloader_naf --> [*]
