gantt
    title Target Codebase Execution Timeline
    dateFormat  s
    axisFormat %S s
    section SupportedLanguage
    section Priority
    section NFRCategory
    section ScreenType
    section Execution
    Execution :t1, 0, 1s
